### ISSUE TITLE
Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by fnordson** [OSM-de/ChangesetAnalyzer#5]
So my first attempt ended up in 500 Internal Server Error. 
Log is filled with this: 

[Tue Jun 16 07:53:58.263858 2020] [-:error] [pid 91535:tid 35066068992] [client xxx.xxx.xxx.xxx:15205] FastCGI: server "/var/run/hcgi/113988" stderr: PHP Warning:  Invalid argument supplied for foreach() in /home/.../change/changeset-analyzer.php on line 100, referer https://...

(Removed IP/paths)

**Comment by kmpoppe** [comment]
Try adding `if ($xml->{$type} != null) {` ... `}` around the foreach-loop that starts at line 100 and try again.
